apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-be
spec:
  selector:
    matchLabels:
      app: flask-be
  replicas: 2
  template:
    metadata:
      labels:
        app: flask-be
    spec:
      containers:
        - name: flask-be
          image: test/examplenode-dev:4
          ports:
            - containerPort: 81