apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-be
  annotations:
    argocd-image-updater.argoproj.io/myimage.pull-secret: pullsecret:argocd/ghcr
spec:
  selector:
    matchLabels:
      app: flask-be
  replicas: 2
  template:
    metadata:
      labels:
        app: flask-be
    spec:
      containers:
        - name: flask-be
          image: ghcr.io/gaston-aqs/flask-be:10
          ports:
            - containerPort: 81
